"""Initial database schema

Revision ID: 22de31fc65d3
Revises: 
Create Date: 2025-09-11 23:11:11.254550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22de31fc65d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('demand', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customer_demand', 'customers', ['demand'], unique=False)
    op.create_index('idx_customer_location', 'customers', ['latitude', 'longitude'], unique=False)
    op.create_table('optimization_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.Enum('CLASSICAL', 'QUANTUM', 'HYBRID', name='optimizationmethod'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_created', 'optimization_jobs', ['created_at'], unique=False)
    op.create_index('idx_job_method', 'optimization_jobs', ['method'], unique=False)
    op.create_index('idx_job_status', 'optimization_jobs', ['status'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('operating_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_warehouse_capacity', 'warehouses', ['capacity'], unique=False)
    op.create_index('idx_warehouse_location', 'warehouses', ['latitude', 'longitude'], unique=False)
    op.create_table('optimization_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('total_co2', sa.Float(), nullable=False),
    sa.Column('avg_delivery_time', sa.Float(), nullable=False),
    sa.Column('routes_used', sa.Integer(), nullable=False),
    sa.Column('optimization_time', sa.Float(), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('convergence', sa.Boolean(), nullable=False),
    sa.Column('routes_data', sa.JSON(), nullable=False),
    sa.Column('assignments_data', sa.JSON(), nullable=False),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['optimization_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('idx_result_cost', 'optimization_results', ['total_cost'], unique=False)
    op.create_index('idx_result_created', 'optimization_results', ['created_at'], unique=False)
    op.create_index('idx_result_job', 'optimization_results', ['job_id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('warehouse_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('transport_mode', sa.String(length=50), nullable=False),
    sa.Column('cost_per_km', sa.Float(), nullable=False),
    sa.Column('co2_per_km', sa.Float(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_route_customer', 'routes', ['customer_id'], unique=False)
    op.create_index('idx_route_distance', 'routes', ['distance_km'], unique=False)
    op.create_index('idx_route_warehouse', 'routes', ['warehouse_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('demand', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('co2', sa.Float(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('delivery_time_hours', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['optimization_results.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assignment_customer', 'assignments', ['customer_id'], unique=False)
    op.create_index('idx_assignment_result', 'assignments', ['result_id'], unique=False)
    op.create_index('idx_assignment_warehouse', 'assignments', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_assignment_warehouse', table_name='assignments')
    op.drop_index('idx_assignment_result', table_name='assignments')
    op.drop_index('idx_assignment_customer', table_name='assignments')
    op.drop_table('assignments')
    op.drop_index('idx_route_warehouse', table_name='routes')
    op.drop_index('idx_route_distance', table_name='routes')
    op.drop_index('idx_route_customer', table_name='routes')
    op.drop_table('routes')
    op.drop_index('idx_result_job', table_name='optimization_results')
    op.drop_index('idx_result_created', table_name='optimization_results')
    op.drop_index('idx_result_cost', table_name='optimization_results')
    op.drop_table('optimization_results')
    op.drop_index('idx_warehouse_location', table_name='warehouses')
    op.drop_index('idx_warehouse_capacity', table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index('idx_job_status', table_name='optimization_jobs')
    op.drop_index('idx_job_method', table_name='optimization_jobs')
    op.drop_index('idx_job_created', table_name='optimization_jobs')
    op.drop_table('optimization_jobs')
    op.drop_index('idx_customer_location', table_name='customers')
    op.drop_index('idx_customer_demand', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
